name: The Healthy Yacht Chef
favicon: null
layout_spectrum: 0.2710421378724277
typography_spectrum: 0.02343336446210742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.07019694661721587
  lightness: 0.5962620701175183
  saturation: 0.340434055775404
  rhythmicContrast: 0.7264009900391102
purpose: []
